GameStore.WebUI/ViewModels/OrderViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using GameStore.Core.Enums;
using GameStore.Resources;

namespace GameStore.WebUI.ViewModels
{
    public class OrderViewModel : EntitySyncViewModel
    {
        [Key]
        [HiddenInput]
        public int OrderId { get; set; }

        [HiddenInput]
        public string SessionKey { get; set; }

        [Display(ResourceType = typeof(GlobalRes), Name = "OrderDate")]
        public DateTime OrderDate { get; set; }

        [Display(ResourceType = typeof(GlobalRes), Name = "OrderStatus")]
        public OrderStatus OrderStatus { get; set; }

        [Display(ResourceType = typeof(GlobalRes), Name = "OrderItems")]
        public ICollection<OrderItemViewModel> OrderItems { get; set; }
    }
}

GameStore.WebUI/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using GameStore.BLL.Interfaces;
using GameStore.BLL.Models;
using GameStore.Core.Enums;
using GameStore.WebUI.Security;
using GameStore.WebUI.ViewModels;

namespace GameStore.WebUI.Controllers
{
    public class OrderController : BaseController
    {
        private readonly IBasketService _basketService;
        private readonly IOrderService _orderService;

        public OrderController(IBasketService basketService,
            IOrderService orderService)
        {
            _basketService = basketService;
            _orderService = orderService;
        }

        [ActionName("Get")]
        [CustomAuthorize(Roles = "User")]
        public ActionResult Get()
        {
            string sessionKey = Session.SessionID;
            OrderModel orderModel = _orderService.GetOrderModelBySessionKey(sessionKey);
            var orderViewModel = Mapper.Map<OrderViewModel>(orderModel);
            return View(orderViewModel);
        }

        [ActionName("New")]
        [CustomAuthorize(Roles = "User")]
        public ActionResult CreateOrder()
        {
            string sessionKey = Session.SessionID;
            OrderModel orderModel = _orderService.GetOrderModelBySessionKey(sessionKey);
            BasketModel basketModel = _basketService.GetBasketModelForUser(sessionKey);

            if (basketModel.BasketItems.Count == 0)
            {
                MessageAttention(
                    "You don't have any items in your basket to create an order. Initially, add some games to your basket.");
                return RedirectToAction("Get", "Game");
            }

            if (orderModel == null)
            {
                _orderService.CreateOrderFromBasket(basketModel);
            }
            else
            {
                _orderService.AddBasketItemsToOrder(basketModel.BasketItems, sessionKey);
            }

            _basketService.CleanBasketForUser(sessionKey);
            MessageSuccess("New items have been successfully added to the order. ");
            return RedirectToAction("Get");
        }

        [HttpPost]
        [ActionName("History")]
        [CustomAuthorize(Roles = "Admin, Manager")]
        public ActionResult GetOrdersByDate(OrderHistoryViewModel orderHistoryViewModel)
        {
            orderHistoryViewModel = orderHistoryViewModel ?? new OrderHistoryViewModel();

            var defaultDate = new DateTime(01, 01, 01, 00, 00, 00);

            if (orderHistoryViewModel.DateFrom == defaultDate)
            {
                orderHistoryViewModel.DateFrom = DateTime.UtcNow.AddYears(-100);
            }

            if (orderHistoryViewModel.DateTo == defaultDate)
            {
                orderHistoryViewModel.DateTo = DateTime.UtcNow.AddDays(-30);
            }

            IEnumerable<OrderModel> orderModels =
                _orderService.GetOrdersByDate(orderHistoryViewModel.DateFrom, orderHistoryViewModel.DateTo);

            var orderViewModels = Mapper.Map<IEnumerable<OrderViewModel>>(orderModels);

            orderHistoryViewModel.Orders = orderViewModels.ToList();

            return View("History", orderHistoryViewModel);
        }

        [HttpGet]
        [ActionName("Orders")]
        [CustomAuthorize(Roles = "Admin, Manager")]
        public ActionResult GetOrdersForLastMonth()
        {
            var orderHistoryViewModel = new OrderHistoryViewModel
            {
                DateFrom = DateTime.UtcNow.AddDays(-30),
                DateTo = DateTime.UtcNow,
            };

            return GetOrdersByDate(orderHistoryViewModel);
        }

        [HttpGet]
        [ActionName("MakeShipped")]
        [CustomAuthorize(Roles = "Admin, Manager")]
        public ActionResult MakeShipped(int orderId, DateTime dateFrom, DateTime dateTo)
        {
            var orderHistoryViewModel = new OrderHistoryViewModel
            {
                DateFrom = dateFrom,
                DateTo = dateTo,
            };

            OrderModel orderModel = _orderService.GetModelById(orderId);

            if (orderModel == null || orderModel.IsReadonly || orderModel.OrderStatus != OrderStatus.Payed)
            {
                return RedirectToAction("History", "Order", orderHistoryViewModel);
            }

            orderModel.OrderStatus = OrderStatus.Shipped;
            _orderService.Update(orderModel);

            MessageSuccess("The order status has been changed to 'Shipped'. ");

            return RedirectToAction("History", "Order", orderHistoryViewModel);
        }
    }
}

GameStore.WebUI/Controllers/PaymentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.ServiceModel;
using System.Text;
using System.Web.Mvc;
using AutoMapper;
using GameStore.BLL.Enums;
using GameStore.BLL.Interfaces;
using GameStore.BLL.Models;
using GameStore.BLL.Models.Payment;
using GameStore.Core;
using GameStore.Resources;
using GameStore.WebUI.PaymentWcfService;
using GameStore.WebUI.ViewModels.Payment;
using GameStore.WebUI.ViewModels.Payment.Info;

namespace GameStore.WebUI.Controllers
{
    public class PaymentController : BaseController
    {
        private const string GameStoreName = "GameStore";

        private readonly IPaymentService _paymentService;
        private readonly IOrderService _orderService;

        public PaymentController(
            IPaymentService paymentService,
            IOrderService orderService)
        {
            _paymentService = paymentService;
            _orderService = orderService;
        }

        #region Helpers

        private static PaymentViewModel GetEmptyPaymentViewModel(PaymentType paymentType)
        {
            var paymentViewModel = new PaymentViewModel
            {
                PaymentType = paymentType,
                PaymentInfoViewModel = new PaymentInfoViewModel
                {
                    BankInfo = new BankInfoViewModel(),
                    TerminalInfo = new TerminalInfoViewModel(),
                    VisaInfo = new VisaInfoViewModel(),
                }
            };

            return paymentViewModel;
        }

        private ActionResult GetBankFileResult(PaymentModel paymentModel)
        {
            var sb = new StringBuilder();

            sb.Append(String.Format("Client full name: {0}.\r\n", paymentModel.PaymentInfo.BankInfo.FullName));
            sb.Append(String.Format("Client credentials: {0}.\r\n", paymentModel.PaymentInfo.BankInfo.Credentials));

            sb.Append("\r\nGame\t\t\tPrice\t\t\tDiscount\r\n");

            foreach (OrderItemModel orderItemModel in paymentModel.OrderItems)
            {
                sb.Append(String.Format("{0}\t\t${1}\t\t-{2}%\r\n",
                    orderItemModel.Game.GameLocalizations.First(loc =>
                        String.Equals(loc.Language.Code, Constants.EnglishLanguageCode, StringComparison.CurrentCultureIgnoreCase))
                        .Name,
                    orderItemModel.Price,
                    orderItemModel.Discount));
            }

            sb.Append(String.Format("Sum: ${0}", paymentModel.Sum));

            string finalString = sb.ToString();

            byte[] bytes = Encoding.UTF8.GetBytes(finalString);
            var result = new FileContentResult(bytes, "text");
            result.FileDownloadName = "BankPayment.txt";
            return result;
        }

        private ActionResult GetVisaResult(PaymentModel paymentModel, PaymentViewModel paymentViewModel)
        {
            var paymentWcfServiceClient = new PaymentWcfServiceClient();

            var visaInfo = Mapper.Map<VisaPaymentInfo>(paymentModel.PaymentInfo.VisaInfo);
            visaInfo.PaymentAmount = paymentModel.Sum;

            var paymentResult = PaymentResult.Failure;

            try
            {
                paymentResult = paymentWcfServiceClient.MakePayment(visaInfo);
            }
            catch (FaultException<ValidationFault> validationEx)
            {
                string errorMessage = string.Empty;
                errorMessage = validationEx.Detail.Details.Aggregate(errorMessage, (current, item) => current + (item.Message + " "));
                ModelState.AddModelError("ServiceError", errorMessage);
            }

            if (paymentResult != PaymentResult.Success)
            {
                ModelState.AddModelError("WrongData", paymentResult.ToString());
                return View("Get", paymentViewModel);
            }

            _orderService.CleanOrderForUser(Session.SessionID);
            MessageSuccess(GlobalRes.OrderMadeSuccessfully);
            return RedirectToAction("Get", "Game");
        }

        #endregion

        [ActionName("Get")]
        [HttpGet]
        public ActionResult MakePayment(PaymentType paymentType)
        {
            var paymentWcfServiceClient = new PaymentWcfServiceClient();
            Guid token = paymentWcfServiceClient.GetToken();

            var visaInfoViewModel = new VisaInfoViewModel
            {
                Token = token,
                Payee = GameStoreName,
            };

            PaymentViewModel paymentViewModel = GetEmptyPaymentViewModel(paymentType);

            paymentViewModel.PaymentInfoViewModel.VisaInfo = visaInfoViewModel;

            return View(paymentViewModel);
        }

        [ActionName("Get")]
        [HttpPost]
        public ActionResult MakePayment(PaymentViewModel paymentViewModel)
        {
            if (ModelState.IsValid)
            {
                string sessionKey = Session.SessionID;
                var paymentInfoModel = Mapper.Map<PaymentInfoModel>(paymentViewModel.PaymentInfoViewModel);

                PaymentModel paymentModel =
                    _paymentService.CreatePaymentModel(sessionKey, paymentViewModel.PaymentType, paymentInfoModel);

                var actions = new Dictionary<PaymentType, Func<PaymentModel, ActionResult>>
                {
                    {PaymentType.Bank, GetBankFileResult},
                    {PaymentType.Visa, model => GetVisaResult(model, paymentViewModel)},
                    {PaymentType.Terminal, model => Json(model, JsonRequestBehavior.AllowGet)}
                };

                return actions[paymentModel.PaymentType](paymentModel);
            }

            return View(paymentViewModel);
        }
    }
}

GameStore.WebUI/Views/Order/Get.cshtml
@using GameStore.BLL.Enums
@using GameStore.WebUI.ViewModels
@model GameStore.WebUI.ViewModels.OrderViewModel

@{
    ViewBag.Title = GlobalRes.Order;
}
<div class="well clearfix">
    <div class="col-sm-12">
        <h3>@ViewBag.Title</h3>
        @if (Model == null || !Model.OrderItems.Any())
        {
            <h5>@GlobalRes.YouDoNotHaveOrder </h5>
        }
        else
        {
            <table class="table table-bordered table-striped">
                <caption>@Html.DisplayFor(m => m.OrderDate)</caption>
                <thead>
                    <tr>
                        <th>@Html.DisplayNameFor(m => m.OrderItems.First().Game.Name)</th>
                        <th>@Html.DisplayNameFor(m => m.OrderItems.First().Price)</th>
                        <th>@Html.DisplayNameFor(m => m.OrderItems.First().Quantity)</th>
                    </tr>
                </thead>
                @foreach (OrderItemViewModel orderItemViewModel in Model.OrderItems)
                {
                    <tr>
                        <td>@Html.DisplayFor(m => orderItemViewModel.Game.Name)</td>
                        <td>@Html.DisplayFor(m => orderItemViewModel.Price)</td>
                        <td>@Html.DisplayFor(m => orderItemViewModel.Quantity)</td>
                    </tr>
                }
            </table>
        }
    </div>
</div>

@if (Model != null && Model.OrderItems.Any())
{
    <div class="well clearfix">
        <div class="col-sm-12">
            <div class="row">
                <div class="col-sm-6 col-md-4">
                    <a href="@Url.Action("Get", "Payment", new {paymentType = PaymentType.Visa})" class="thumbnail nounderline">
                        <img src="@Url.Content("~/Content/images/visa.png")" alt="Visa" width="336">
                        <div class="caption">
                            <h3>@GlobalRes.Visa</h3>
                            <p>@GlobalRes.VisaDescription</p>
                        </div>
                    </a>
                </div>

                <div class="col-sm-6 col-md-4">
                    <a href="@Url.Action("Get", "Payment", new {paymentType = PaymentType.Bank})" class="thumbnail nounderline">
                        <img src="@Url.Content("~/Content/images/bank.png")" alt="Bank" width="336">
                        <div class="caption">
                            <h3>@GlobalRes.Bank</h3>
                            <p>@GlobalRes.BankDescription</p>
                        </div>
                    </a>
                </div>

                <div class="col-sm-6 col-md-4">
                    <a href="@Url.Action("Get", "Payment", new {paymentType = PaymentType.Terminal})" class="thumbnail nounderline">
                        <img src="@Url.Content("~/Content/images/ibox.png")" alt="IBox" width="336">
                        <div class="caption">
                            <h3>@GlobalRes.IBox</h3>
                            <p>@GlobalRes.IBoxDescription</p>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
}

GameStore.WebUI/Views/Order/History.cshtml
@using GameStore.Core.Enums
@using GameStore.WebUI.ViewModels
@model GameStore.WebUI.ViewModels.OrderHistoryViewModel

@{
    ViewBag.Title = GlobalRes.OrdersHistory;
}

<div class="well">
    @using (Html.BeginForm("History", "Order", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary()

        <fieldset>
            <legend>@GlobalRes.PickDateForOrders</legend>
            
            @Html.EditorForModel()

            <div class="form-group">
                <div class="col-lg-10 col-lg-offset-2">
                    <button type="submit" class="btn btn-primary">@GlobalRes.Apply</button>
                </div>
            </div>
        </fieldset>
    }
</div>


@if (Model.Orders != null && Model.Orders.Any())
{
    <h3>@ViewBag.Title</h3>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>@Html.LabelFor(x => Model.Orders.First().OrderDate)</th>
                <th>@Html.LabelFor(x => Model.Orders.First().OrderStatus)</th>
                <th></th>
            </tr>
        </thead>
        <tbody>

            @foreach (OrderViewModel orderViewModel in Model.Orders)
            {
                <tr>
                    <td>@Html.DisplayFor(o => orderViewModel.OrderDate)</td>
                    <td>
                        @{string orderStatus = EnumHelper<OrderStatus>.GetEnumDescription(orderViewModel.OrderStatus.ToString()); }
                        @orderStatus
                    </td>
                    <td>
                        @if (orderViewModel.OrderStatus == OrderStatus.Payed)
                        {
                            @Html.ActionLink(GlobalRes.MakeShipped, "MakeShipped", "Order",
                            new {@orderId = orderViewModel.OrderId, @dateFrom = Model.DateFrom, @dateTo = Model.DateTo},
                            new {@class = "btn btn-default"})
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>

}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}