GameStore.WebUI/ViewModels/BanViewModel.cs
using GameStore.BLL.Enums;

namespace GameStore.WebUI.ViewModels
{
    public class BanViewModel
    {
        public BanPeriod BanPeriod { get; set; }
    }
}

GameStore.WebUI/ViewModels/CommentViewModel.cs
using System.ComponentModel.DataAnnotations;
using GameStore.Resources;

namespace GameStore.WebUI.ViewModels
{
    public class CommentViewModel : EntityViewModel
    {
        [Key]
        public int CommentId { get; set; }

        public int GameId { get; set; }

        public int? ParentCommentId { get; set; }

        [Required]
        [Display(ResourceType = typeof(GlobalRes), Name = "Name")]
        public string Name { get; set; }

        [Required]
        [Display(ResourceType = typeof(GlobalRes), Name = "Body")]
        public string Body { get; set; }
    }
}

GameStore.WebUI/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using AutoMapper;
using GameStore.BLL.Enums;
using GameStore.BLL.Interfaces;
using GameStore.BLL.Models;
using GameStore.WebUI.Filters;
using GameStore.WebUI.Helpers;
using GameStore.WebUI.Security;
using GameStore.WebUI.ViewModels;

namespace GameStore.WebUI.Controllers
{
    [ExceptionLoggingFilter]
    [PerformanceLoggingFilter]
    public class CommentController : BaseController
    {
        private readonly IGameService _gameService;
        private readonly ICommentService _commentService;

        /// <summary>
        /// Initializes a new instance of the <see cref="CommentController"/> class.
        /// </summary>
        /// <param name="gameService">The game service.</param>
        /// <param name="commentService">The comment service.</param>
        public CommentController(
            IGameService gameService,
            ICommentService commentService)
        {
            _gameService = gameService;
            _commentService = commentService;
        }

        /// <summary>
        /// Gets all comments for a game specified by the key.
        /// </summary>
        /// <param name="key">The key.</param>
        /// <returns></returns>
        [HttpGet]
        [ActionName("Comments")]
        public ActionResult GetCommentsForGame(string key)
        {
            GameModel gameModel = _gameService.GetGameModelByKey(key);
            IEnumerable<CommentModel> commentModels = gameModel.Comments;
            var commentViewModels = Mapper.Map<IEnumerable<CommentViewModel>>(commentModels);
            return View(commentViewModels);
        }

        /// <summary>
        /// Adds the comment for game specified by the key.
        /// </summary>
        /// <param name="key">The key.</param>
        /// <param name="commentViewModel">The comment view model.</param>
        /// <returns></returns>
        [HttpPost]
        [ActionName("NewComment")]
        public ActionResult AddCommentForGame(string key, CommentViewModel commentViewModel)
        {
            var commentModel = Mapper.Map<CommentModel>(commentViewModel);
            _commentService.Add(commentModel, key);
            MessageSuccess("The comment has been added successfully!");
            return RedirectToAction("Comments", new {key});
        }

        /// <summary>
        /// Removes the comment.
        /// </summary>
        /// <param name="id">The comment identifier.</param>
        /// <returns></returns>
        [ActionName("Remove")]
        [CustomAuthorize(Roles = "Admin, Moderator")]
        public ActionResult RemoveComment(int id)
        {
            _commentService.Remove(id);
            MessageSuccess("The comment has been removed successfully!");
            return RedirectToAction("Comments");
        }

        [ActionName("Ban")]
        [HttpGet]
        [CustomAuthorize(Roles = "Admin, Moderator")]
        public ActionResult Ban()
        {
            var banViewModel = new BanViewModel();
            return View(banViewModel);
        }

        [ActionName("Ban")]
        [HttpPost]
        [CustomAuthorize(Roles = "Admin, Moderator")]
        public ActionResult Ban(BanViewModel banViewModel)
        {
            string message = String.Format("The user was banned on the next period: {0}.",
                EnumHelper<BanPeriod>.GetEnumDescription(banViewModel.BanPeriod.ToString()));
            MessageAttention(message);
            return RedirectToAction("Get", "Game");
        }
    }
}

GameStore.WebUI/Views/Comment/Ban.cshtml
@model GameStore.WebUI.ViewModels.BanViewModel

@{
    ViewBag.Title = GlobalRes.Ban;
}

<h3>Ban</h3>
@using (Html.BeginForm("Ban", "Comment", FormMethod.Post))
{
    <div class="well">
        <div class="form-group">
            @Html.EnumRadioButtonListFor(m => m.BanPeriod)
            <button type="submit" class="btn btn-danger" data-toggle="modal" data-target="#modal-ban">@GlobalRes.Ban</button>

            <!-- Modal -->
            <div class="modal fade" id="modal-ban" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="myModalLabel">@GlobalRes.Warning</h4>
                        </div>
                        <div class="modal-body">
                            @GlobalRes.BanConfirmation
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-danger">@GlobalRes.Ban</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

GameStore.WebUI/Views/Comment/Comments.cshtml
@using GameStore.WebUI.ViewModels
@model IEnumerable<GameStore.WebUI.ViewModels.CommentViewModel>

@{
    ViewBag.Title = GlobalRes.Comments;
}

<h3>@ViewBag.Title</h3>@if (Model == null || !Model.Any())
{
    <h4>@GlobalRes.ThereAreNoComments</h4>
}
else
{
    <div class="well">

        @foreach (CommentViewModel comment in Model)
        {
            <div class="comment">
                <div class="comment-id">
                    @Html.HiddenFor(c => comment.CommentId)
                </div>

                @if (User != null && (User.IsInRole("Admin") || User.IsInRole("Moderator")))
                {
                    <div class="form-group pull-right">
                        <button class="btn btn-default btn-reply">@GlobalRes.Reply</button>
                        <button class="btn btn-primary btn-quote">@GlobalRes.Quote</button>
                        @{ string modalId = "modal-remove-" + comment.CommentId; }
                        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#@modalId">@GlobalRes.Remove</button>

                        <!-- Modal -->
                        <div class="modal fade" id="@modalId" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                        <h4 class="modal-title" id="myModalLabel">@GlobalRes.Warning</h4>
                                    </div>
                                    <div class="modal-body">
                                        @GlobalRes.RemoveCommentConfirmation
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">@GlobalRes.Cancel</button>
                                        @Html.ActionLink(@GlobalRes.Remove, "Remove", "Comment", new { id = comment.CommentId }, new { @class = "btn btn-danger" })
                                    </div>
                                </div>
                            </div>
                        </div>

                        @Html.ActionLink(@GlobalRes.Ban, "Ban", "Comment", null, new { @class = "btn btn-default" })
                    </div>
                }
                <div class="form-group">
                    @Html.Label(comment.Name, new { @class = "comment-name" })
                </div>
                <div class="form-group">
                    <div class="comment-body">
                        @Html.GetCommentBodyWithDecodedTags(comment.Body)
                    </div>
                    <hr>
                </div>
            </div>
        }
    </div>
}
<div class="well">
    @Html.Partial("_AddComment", new CommentViewModel())
</div>

GameStore.WebUI/Views/Comment/_AddComment.cshtml
@model GameStore.WebUI.ViewModels.CommentViewModel

@using (Html.BeginForm("NewComment", "Comment", FormMethod.Post, new {@class = "form-horizontal"}))
{
    <fieldset>
        <legend>@GlobalRes.NewComment</legend>

        @Html.AntiForgeryToken()
        @Html.ValidationSummary()
        
        @Html.HiddenFor(model => model.GameId)
        @Html.HiddenFor(model => model.ParentCommentId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, new {@class = "col-lg-1 control-label"})
            <div class="col-lg-3">
                @Html.TextBoxFor(model => model.Name, null, new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Body, new {@class = "col-lg-1 control-label"})
            <div class="col-lg-10 clearfix">
                @Html.TextAreaFor(model => model.Body, new {@class = "form-control"})
                @Html.ValidationMessageFor(model => model.Body)
            </div>
        </div>

        <div class="form-group">
            <div class="col-lg-4 col-lg-offset-1">
                @Html.ActionLink(GlobalRes.ToList, "Get", "Game", null, new {@class = "btn btn-default"})
                <button type="submit" class="btn btn-success">@GlobalRes.Submit</button>
            </div>
        </div>
    </fieldset>
}